name: greenora_pos
description: A new Flutter Supabase project.
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.0
  connectivity_plus: ^4.0.1

  # ==== Supabase ====
  supabase_flutter: ^2.5.4

  # ==== State Management ====
  flutter_riverpod: ^2.5.1
  # jika pakai provider, hapus riverpod dan pakai ini:
  # provider: ^6.1.2

  # ==== PDF & PRINTING ====
  pdf: ^3.10.7
  printing: ^5.10.4

  # ==== Utilitas ====
  intl: ^0.19.0
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/logo_green.png
   - assets/images/jus_alpukat.png
   - assets/images/jus_bluberi.png
   - assets/images/jus_kiwi.png
   - assets/images/jus_mangga.png
   - assets/images/jus_pepaya.png
   - assets/images/jus_semangka.png
   - assets/images/jus_stroberi.png
   - assets/images/jus_timun.png
   - assets/images/jus_tomat.png
   - assets/images/salad_sayur.png
   - assets/images/salad_gulung.png
   - assets/images/ayam_panggang-dn.png

   